version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn django_movie.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    depends_on:
      - web
  redis:
    image: redis:5-alpine
    volumes:
      - rd_redis_data:/home/app/web/redis
  celery:
    build: .
    command: celery -A sitecompany worker
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - redis
  celerybeat:
    build: .
    command: celery -A sitecompany beat
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume:
  rd_redis_data:
